version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: doc_management_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    external: false